-- =============================================================================
-- Load Certificate-to-Proposal Mappings from CSV
-- Creates stg_policy_proposal_mappings table and bulk loads from CSV file
-- Usage: sqlcmd -S server -d database -i sql/transforms/08a-load-certificate-mappings.sql
-- =============================================================================

SET NOCOUNT ON;

PRINT '============================================================';
PRINT 'LOAD: Certificate-to-Proposal Mappings';
PRINT '============================================================';
PRINT '';

-- =============================================================================
-- Step 1: Create/recreate stg_policy_proposal_mappings table
-- =============================================================================
PRINT 'Step 1: Creating stg_policy_proposal_mappings table...';

DROP TABLE IF EXISTS [$(ETL_SCHEMA)].[stg_policy_proposal_mappings];

CREATE TABLE [$(ETL_SCHEMA)].[stg_policy_proposal_mappings] (
    ProposalId NVARCHAR(100) NOT NULL,
    CertificateId NVARCHAR(50) NOT NULL,
    PRIMARY KEY (CertificateId)
);

PRINT '  ✓ Table created';
PRINT '';

-- =============================================================================
-- Step 2: Bulk load from CSV file
-- =============================================================================
PRINT 'Step 2: Bulk loading from certificate-proposal-mappings.csv...';
PRINT '  Note: CSV file must be accessible to SQL Server';
PRINT '  Expected format: ProposalId,CertificateId (no header)';
PRINT '';

-- NOTE: The CSV file path must be accessible from SQL Server's perspective
-- For local development, place the file in a location SQL Server can read
-- For Azure SQL, use OPENROWSET with BULK option or pre-upload to Azure Blob

-- BULK INSERT approach (for SQL Server with file system access)
/*
BULK INSERT [$(ETL_SCHEMA)].[stg_policy_proposal_mappings]
FROM 'certificate-proposal-mappings.csv'
WITH (
    FIELDTERMINATOR = ',',
    ROWTERMINATOR = '\n',
    FIRSTROW = 1,
    TABLOCK
);

DECLARE @rows_loaded INT = @@ROWCOUNT;
PRINT '  ✓ Rows loaded: ' + CAST(@rows_loaded AS VARCHAR);
*/

-- Alternative: Use application code to insert rows
-- The TypeScript proposal builder will handle this through standard INSERTs
PRINT '  ⚠️ Bulk insert commented out - use TypeScript bulk insert or load manually';
PRINT '  ⚠️ File generated by proposal builder: certificate-proposal-mappings.csv';
PRINT '';

-- =============================================================================
-- Step 3: Validate mappings
-- =============================================================================
PRINT 'Step 3: Validating mappings...';

DECLARE @mapping_count INT = (SELECT COUNT(*) FROM [$(ETL_SCHEMA)].[stg_policy_proposal_mappings]);
PRINT '  Total mappings: ' + CAST(@mapping_count AS VARCHAR);

DECLARE @unique_proposals INT = (SELECT COUNT(DISTINCT ProposalId) FROM [$(ETL_SCHEMA)].[stg_policy_proposal_mappings]);
PRINT '  Unique proposals: ' + CAST(@unique_proposals AS VARCHAR);

DECLARE @unique_certs INT = (SELECT COUNT(DISTINCT CertificateId) FROM [$(ETL_SCHEMA)].[stg_policy_proposal_mappings]);
PRINT '  Unique certificates: ' + CAST(@unique_certs AS VARCHAR);

-- Check for invalid certificate IDs (not in raw data)
DECLARE @invalid_certs INT = (
    SELECT COUNT(*)
    FROM [$(ETL_SCHEMA)].[stg_policy_proposal_mappings] m
    WHERE NOT EXISTS (
        SELECT 1 
        FROM [$(ETL_SCHEMA)].[input_certificate_info] ci
        WHERE CAST(ci.CertificateId AS NVARCHAR(50)) = m.CertificateId
    )
);

IF @invalid_certs > 0
BEGIN
    PRINT '  ⚠️ Warning: ' + CAST(@invalid_certs AS VARCHAR) + ' certificates in mapping not found in input data';
END
ELSE
BEGIN
    PRINT '  ✓ All certificate IDs are valid';
END

PRINT '';
PRINT '============================================================';
PRINT 'LOAD COMPLETE';
PRINT '============================================================';
